services:
  web:
    build:
      context: ./
      dockerfile: ./docker/production.Dockefile
    ports:
      - 3000:3000
    env_file: ./environments/production.env
    command: ["npm", "run", "start"]